# Generated by Django 4.2.4 on 2023-08-13 14:23

from django.db import migrations, models
import main.Manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathHouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_key', models.IntegerField(default=0, unique=True, verbose_name='Номер ключа')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Время начало')),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('my_type', models.CharField(choices=[('MEN', 'Мужской'), ('WOMEN', 'Женский')], max_length=5, verbose_name='Пол')),
                ('hours', models.CharField(choices=[('1', 'час'), ('2', '2 часа'), ('3', '3 часа'), ('4', '4 часа'), ('5', '5 часов')], max_length=5, verbose_name='На сколько забранировано')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очередь',
                'ordering': ['number_key'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
            managers=[
                ('objects', main.Manager.UserManager()),
            ],
        ),
    ]
