# Generated by Django 4.2.4 on 2023-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_off',
            field=models.TimeField(verbose_name='Оставшееся время'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Номер ящика'),
        ),
    ]
