# Generated by Django 4.2.4 on 2023-08-03 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_date_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_off',
        ),
        migrations.AddField(
            model_name='user',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время когда он зашел'),
            preserve_default=False,
        ),
    ]
