# Generated by Django 4.2.4 on 2023-08-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_date_off_user_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
