# Generated by Django 4.2.4 on 2023-08-03 10:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_date_start_remove_user_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathHouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_key', models.IntegerField(default=0, unique=True, verbose_name='Номер ключа')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Время начало')),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очередь',
                'ordering': ['number_key'],
            },
        ),
    ]
