# Generated by Django 4.2.4 on 2023-08-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bathhousemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhousemodel',
            name='my_type',
            field=models.CharField(choices=[('MEN', 'Мужской'), ('WOMEN', 'Женский')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
