# Generated by Django 4.2.4 on 2023-08-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bathhousemodel_my_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhousemodel',
            name='hours',
            field=models.CharField(choices=[('1', 'час'), ('2', '2 часа'), ('3', '3 часа'), ('4', '4 часа'), ('5', '5 часа')], default=1, max_length=5, verbose_name='На сколько забранировано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bathhousemodel',
            name='my_type',
            field=models.CharField(choices=[('MEN', 'Мужской'), ('WOMEN', 'Женский')], max_length=5, verbose_name='Пол'),
        ),
    ]
